name: fs_hub_backend
description: A simple shelf-based backend for fs_hub
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  mysql_client: ^0.0.27
  dart_jsonwebtoken: ^2.7.1
  dotenv: ^4.2.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
